In [1]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

# Tensors

## Scalar

In [2]:
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim, scalar.shape

(0, torch.Size([]))

## Vector

In [4]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim, vector.shape

(1, torch.Size([2]))

## MATRIX 

In [6]:
MATRIX = torch.tensor([[7,8],[9,10]])

In [7]:
MATRIX.ndim, MATRIX.shape, MATRIX[1]

(2, torch.Size([2, 2]), tensor([ 9, 10]))

## TENSOR

In [8]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [9]:
TENSOR.ndim, TENSOR.shape, TENSOR[0]

(3,
 torch.Size([1, 3, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

## Random Tensors

In [12]:
# they are importan for starting neural networks with randome numbers and start. 
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.5584, 0.4969, 0.1818, 0.3186],
        [0.8550, 0.6341, 0.8922, 0.9434],
        [0.4377, 0.6196, 0.1235, 0.8625]])

In [14]:
rand_tensor.ndim, rand_tensor.shape, rand_tensor[0]

(2, torch.Size([3, 4]), tensor([0.5584, 0.4969, 0.1818, 0.3186]))

In [15]:
random_img_size_tensor = torch.rand(224,224,3) # height, width, color channels (RGB)
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [17]:
zeros = torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
ones = torch.ones(size=(3,4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating a range of tensors and tensors like

In [22]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                               dtype=torch.float32, # what datatype is your tensor
                               device=None, # what device is your tensor on? CPU or GPU
                               requires_grad=False) # does it need gradient for autograd
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
float_32_tensor + float_16_tensor

tensor([ 6., 12., 18.])

In [35]:
int_32_tensor = torch.tensor([3,6,9], 
                               dtype=torch.int32, # what datatype is your tensor
                               device=None, # what device is your tensor on? CPU or GPU
                               requires_grad=False) # does it need gradient for autograd

int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [38]:
int_32_tensor.dtype, int_32_tensor.device, int_32_tensor.requires_grad

(torch.int32, device(type='cpu'), False)

## ADD, SUBSTRACT, MULTIPLY, DIVIDE

In [47]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([[10,10,10],[10,10,10],[10,10,10]])
tensor1 + tensor2

tensor([[11, 12, 13],
        [11, 12, 13],
        [11, 12, 13]])

In [48]:
tensor1 - tensor2

tensor([[-9, -8, -7],
        [-9, -8, -7],
        [-9, -8, -7]])

In [50]:
tensor1 * tensor2

tensor([[10, 20, 30],
        [10, 20, 30],
        [10, 20, 30]])

In [51]:
tensor1 / tensor2

tensor([[0.1000, 0.2000, 0.3000],
        [0.1000, 0.2000, 0.3000],
        [0.1000, 0.2000, 0.3000]])

In [52]:
torch.matmul(tensor1, tensor2) # T is transpose

tensor([60, 60, 60])

In [56]:
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.matmul(tensor_a.T, tensor_b)

tensor([[ 76, 103],
        [100, 136]])

In [55]:
tensor_a.T

tensor([[1, 3, 5],
        [2, 4, 6]])

## Finding the min, max, mean, sum etc(tensor, agg)

In [62]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), torch.max(x), torch.mean(x.float()), torch.sum(x), torch.std(x.float()), torch.var(x.float()) 

(tensor(0),
 tensor(90),
 tensor(45.),
 tensor(450),
 tensor(30.2765),
 tensor(916.6667))

In [63]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing, and unsqueezing tensors.

In [110]:
x=torch.arange(1,10)

In [111]:
# add dimenstion
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [71]:
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [72]:
x=torch.arange(1,11)

In [73]:
x_reshaped = x.reshape(2,5)
x_reshaped

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [92]:
# change the view
z = x.view(1,9)
z[0,0] = 1
z,x


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [94]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [113]:
print(x_reshaped.shape)
x_squeezed = x_reshaped.squeeze()
print(x_squeezed.shape)

torch.Size([1, 9])
torch.Size([9])


In [105]:
torch.unsqueeze(x_reshaped,1)

tensor([[[ 1,  2,  3,  4,  5]],

        [[ 6,  7,  8,  9, 10]]])